version: "3"

volumes:
  db_data:

networks:
  web:
  db:

services:
  # ************************************************************* #
  # PostgreSQL
  # ************************************************************* #
  pebmed-db:
    image: postgres:12.2-alpine
    container_name: pebmed-db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./db/.env.example
    networks:
      - db
    restart: always
    ports:
      - 5432:5432

  # ************************************************************* #
  # Api using Express
  # ************************************************************* #
  pebmed-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pebmed-api
    networks:
      - web
      - db
    depends_on:
      - pebmed-db
    volumes:
      - ./pebmed-api:/backend
    ports: 
      - 3333:3333
    command: bash -c "npm run migrations && npm run prod:server"